/bin/bash: /h/u9/c1/00/lijiax50/miniconda3/envs/r3d3_hanabi/lib/libtinfo.so.6: no version information available (required by /bin/bash)

EnvironmentNameNotFound: Could not find conda environment: r3d_hanabi
You can list all discoverable environments with `conda info --envs`.



A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/r3d2_main.py", line 439, in <module>
    train(args)
  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/r3d2_main.py", line 119, in train
    common_utils.set_all_seeds(args.seed)
  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/common_utils/helper.py", line 181, in set_all_seeds
    torch.manual_seed(rand_seed + 2)
  File "/h/u9/c1/00/lijiax50/miniconda3/envs/r3d3_hanabi/lib/python3.9/site-packages/torch/random.py", line 46, in manual_seed
    return default_generator.manual_seed(seed)
/h/u9/c1/00/lijiax50/miniconda3/envs/r3d3_hanabi/lib/python3.9/site-packages/torch/random.py:46: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  return default_generator.manual_seed(seed)
/h/u9/c1/00/lijiax50/miniconda3/envs/r3d3_hanabi/lib/python3.9/site-packages/huggingface_hub/file_download.py:943: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/r3d2_main.py", line 439, in <module>
    train(args)
  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/r3d2_main.py", line 234, in train
    act_groups.append(act_group_type(**act_group_args))
  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/create.py", line 141, in __init__
    super().__init__(devices, agent, method_batchsize)
  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/create.py", line 108, in __init__
    self.model_runners = create_model_runners(agent, self.devices, method_batchsize)
  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/create.py", line 93, in create_model_runners
    runner = BatchRunner(agent, dev, methods)
  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/create.py", line 69, in __init__
    self.agent = agent.clone(device)
  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/r2d2.py", line 116, in clone
    cloned = type(self)(
  File "/h/u9/c1/00/lijiax50/miniconda3/envs/r3d3_hanabi/lib/python3.9/site-packages/torch/jit/_script.py", line 292, in init_then_script
    original_init(self, *args, **kwargs)
  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/r2d2.py", line 44, in __init__
    self.online_net = TextLSTMNet(
  File "/h/u9/c1/00/lijiax50/miniconda3/envs/r3d3_hanabi/lib/python3.9/site-packages/torch/jit/_script.py", line 292, in init_then_script
    original_init(self, *args, **kwargs)
  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/q_net.py", line 489, in __init__
    self.act_toks = self.load_json(path)
  File "/h/u9/c1/00/lijiax50/Documents/R3D2/pyhanabi/q_net.py", line 599, in load_json
    return torch.tensor(d["input_ids"], device=self.device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

